apiVersion: stable.che.eclipse.org/v1
kind: CheService
metadata:
 name: io.typefox.theia-ide.che-service
spec:
 version: 0.0.1
 services:
   - apiVersion: v1
     kind: Service
     metadata:
       name: io.typefox.theia-ide.che-service.mainservice
     spec:
       selector:
         app: theia
       ports:
       - protocol: TCP
         port: 80
         targetPort: 8080
 pods:
   - apiVersion: v1
     kind: Pod
     metadata:
       name: io.typefox.theia-ide.che-service.mainpod
     spec:
       selector:
         app: theia
       containers:
         - image: eclipse/che-theia:nightly
           labels:
             che.eclipse.org/container-name: theia-core
           name: theia
           env:
             - name: THEIA_PLUGINS
               value: ${THEIA_PLUGINS}
           volumeMounts:
             - mountPath: "/projects"
               name: projects   
         - image: maven:latest
           labels:
             che.eclipse.org/container-name: theia-maven-sidecar
           name: theia-sidecar
     volumes:
       - name: projects
         persistentVolumeClaim:
         claimName: projects
 commands:
   - apiVersion: stable.che.eclipse.org/v1
     kind: CheCommand
     metadata:
       name: mvn-clean
     spec:
       target-label-selector: "che.eclipse.org/container-name= theia-maven-sidecar"
       working-dir: "$(project)"
       command: ["mvn", "clean", "install"]  
