apiVersion: v1
kind: CheService
metadata:
  name: io.typefox.theia-ide.che-service
spec:
 version: 0.0.1 
 containers:
   - image: eclipse/che-theia:nightly
     resources:
       requests:
         memory:200Mi
     env:
       - name: THEIA_PLUGINS
         value: ${THEIA_PLUGINS}
     volumes:
       - mountPath: "/projects"
         name: projects   
     servers:
       - name: theia
          attributes:
             type: ide
          port: '3000'
          protocol: http